VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Form_frmMenueExtraSmall"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
' frmAuftragEdit

Option Compare Database
Option Explicit

Private Sub cmd0_Click()
    basMenueExtraSmall.FormularSchlieﬂen
End Sub

Private Sub cmd1_Click()
    basMenueExtraSmall.CreateAuftrag
End Sub
